name: Lets Start RAVANOFFICIAL
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@all
        with:
          find: "AsunaRobot"
          replace: "RAVAN-OFFICIAL"
      - name: Pull All Updates        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '👣RAVAN-OFFICIAL'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: KINGOFASURA
          commit_user_email: +KINGOFASURA@users.noreply.github.com
          commit_author: KINGOFASURA <+KINGOFASURA@users.noreply.github.com>
